"""Remove not null de dia_semana

Revision ID: 134849a2f20d
Revises: 81c342805969
Create Date: 2025-06-22 22:42:02.696539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '134849a2f20d'
down_revision = '81c342805969'
branch_labels = None
depends_on = None

def upgrade():
    op.alter_column('agendas_medicos', 'dia_semana', nullable=True)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendas_medicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia_semana', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
