"""corrigindo relacionamentos de agendamento

Revision ID: 351cd310907e
Revises: 96abe6be91c7
Create Date: 2025-06-22 22:20:56.374556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '351cd310907e'
down_revision = '96abe6be91c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('horario', sa.Time(), nullable=False))
        batch_op.drop_column('observacoes')
        batch_op.drop_column('consentimento')
        batch_op.drop_column('data_hora')
        batch_op.drop_column('status')
        batch_op.drop_column('duracao')
        batch_op.drop_column('finalidade_dados')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalidade_dados', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('duracao', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_hora', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('consentimento', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('horario')
        batch_op.drop_column('data')

    # ### end Alembic commands ###
