"""Remove coluna dia_semana

Revision ID: 5c4636ef9a28
Revises: 134849a2f20d
Create Date: 2025-06-22 22:42:34.255770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c4636ef9a28'
down_revision = '134849a2f20d'
branch_labels = None
depends_on = None


def upgrade():
    op.drop_column('agendas_medicos', 'dia_semana')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendas_medicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia_semana', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
