"""Adiciona campo data em AgendaMedico

Revision ID: 81c342805969
Revises: 351cd310907e
Create Date: 2025-06-22 22:38:05.379681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c342805969'
down_revision = '351cd310907e'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Adiciona a nova coluna como opcional primeiro
    op.add_column('agendas_medicos', sa.Column('data', sa.Date(), nullable=True))
    
    # 2. Atualiza os registros existentes com uma data padrão
    op.execute("UPDATE agendas_medicos SET data = '2025-06-25'")
    
    # 3. Torna a coluna obrigatória (NOT NULL)
    op.alter_column('agendas_medicos', 'data', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendas_medicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dia_semana', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###
