"""Adiciona campo agenda_id ao agendamento

Revision ID: 96abe6be91c7
Revises: 213ad827a51e
Create Date: 2025-06-22 22:12:45.050757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96abe6be91c7'
down_revision = '213ad827a51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agenda_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'agendas_medicos', ['agenda_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('agenda_id')

    # ### end Alembic commands ###
